version: '3'

volumes:
  data_volume:
    external: true

services: 
  web:
    build: ./web
    ports: 
      - "5000:5000"
    links: 
      - db
    volumes:
      - /usr/src/app/credential_keys
      - /usr/src/app/uploads
      - /usr/src/app/BTuploads
      - /usr/src/app/zipfolder

  db:
    build: ./db


